### ISSUE TITLE
Navbar Design

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Diagon-Alley#21]
![Screenshot 2022-10-17 211719](https://user-images.githubusercontent.com/50085447/196227131-22ff99bd-501f-423f-89cf-467c549226f1.png)

do this one as a component

**Comment by Dhanuka99** [comment]
I am Interested this issue can I fix ?

**Comment by IT21169076** [comment]
can i fix this issue ?

**Comment by manojku1803** [comment]
Please assign me this.

**Comment by MadhushaPrasad** [comment]
@manojku1803 assigned, now you can work on this issue

**Comment by IT21169076** [comment]
can i implement this one

**Comment by MadhushaPrasad** [comment]
> can i implement this one

yah sure
