### ISSUE TITLE
Home Page - Contact Us Section

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Diagon-Alley#26]
do this as a component
![Screenshot 2022-10-17 211623](https://user-images.githubusercontent.com/50085447/196228215-e14dc3f1-8042-4bc9-8a49-f072527ff7db.png)

**Comment by Dhanuka99** [comment]
I am Interested this issue can I fix ?

**Comment by IT21169076** [comment]
i  am interested this issue can i fix?

**Comment by IndudiniThennakoon** [comment]
> i am interested this issue can i fix?

sure shali

**Comment by Janani-Balasooriya** [comment]
I can develop this Home Page - Contact Us Section. Could you please assign me to this issue?
Thank you, @MadhushaPrasad !

**Comment by MadhushaPrasad** [comment]
> I can develop this Home Page - Contact Us Section. Could you please assign me to this issue? Thank you, @MadhushaPrasad !

yah sure
