### ISSUE TITLE
Start Up Page

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Diagon-Alley#27]
![Startup](https://user-images.githubusercontent.com/50085447/196236328-e46c00e0-8ab8-4df5-a794-f1b6008712b8.png)

**Comment by Dhanuka99** [comment]
I am Interested this issue can I fix ?

**Comment by MadhushaPrasad** [comment]
@Dhanuka99 sure

**Comment by MadhushaPrasad** [comment]
how is the progress on this issue? @Dhanuka99

**Comment by Sandaru-Dev** [comment]
Hi @MadhushaPrasad, Can you please assign me to this issue?

**Comment by Dhanuka99** [comment]
can you assign me this issue ?

**Comment by MadhushaPrasad** [comment]
> can you assign me this issue ?

please assign for another task just like #21 . I think its good for you

**Comment by IT21158186** [comment]
@MadhushaPrasad  Can you please assign this task to me? I'll do my best for this design.
