### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Diagon-Alley#28]
![Login (1)](https://user-images.githubusercontent.com/50085447/196235630-9b81464f-c64e-437e-8a29-849b32eeaa82.png)

**Comment by IndudiniThennakoon** [comment]
Can I work with this issue?

**Comment by MadhushaPrasad** [comment]
sure

**Comment by Poonamraut040** [comment]
can I work on this issue?

**Comment by MadhushaPrasad** [comment]
> can I work on this issue?

@IndudiniThennakoon are you work on this yet? If not, Can I pass this to @Poonamraut040 ??

**Comment by MadhushaPrasad** [comment]
> can I work on this issue?

yah sure, You can work on it

**Comment by MadhushaPrasad** [comment]
@Poonamraut040 can you send me a update on this issue?
