### ISSUE TITLE
Update Readme with figma design link

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Diagon-Alley#29]
https://www.figma.com/file/dz4JS3XBiGzTDGGIQ3PczB/Diagon-Alley?node-id=20%3A782

**Comment by Tatwansh** [comment]
hey, can I work on this issue?

**Comment by MadhushaPrasad** [comment]
@Tatwansh ask from it @IndudiniThennakoon

**Comment by IndudiniThennakoon** [comment]
@Tatwansh yeah sure..

**Comment by Tatwansh** [comment]
@MadhushaPrasad do I have to use the content from the figma link given above
