### ISSUE TITLE
Footer design

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Diagon-Alley#30]
![Screenshot 2022-10-17 222253](https://user-images.githubusercontent.com/50085447/196237285-dd688b4c-e097-4048-b9dc-8367dfa42514.png)

**Comment by MadhushaPrasad** [comment]
sure,no problem

**Comment by Kaushals112** [comment]
please assign this task to me

**Comment by Kaushals112** [comment]
sir i have to use above photo or we can make my own footer design?

**Comment by MadhushaPrasad** [comment]
First of all don’t say me Sir😊 And it as the Figma design.

Here is the Figma link https://www.figma.com/file/dz4JS3XBiGzTDGGIQ3PczB/Diagon-Alley?node-id=0%3A1

**Comment by Kaushals112** [comment]
ok i am working on it

**Comment by MadhushaPrasad** [comment]
any update? @Kaushals112

**Comment by Kaushals112** [comment]
yes sir done

**Comment by Kaushals112** [comment]
thanks i learn to use figma

**Comment by Kaushals112** [comment]
sir when i push my branch file its writting acess denied, how i can fix it

**Comment by Kaushals112** [comment]
its writting merging block

**Comment by DishaKD** [comment]
Can I work on that issue

**Comment by MadhushaPrasad** [comment]
> Can I work on that issue

Yes, for sure. Please don't hesitate to include a screenshot here once the UI implementation of this footer area is finished.

**Comment by ANIKETRAJ28** [comment]
can i work on this

**Comment by MadhushaPrasad** [comment]
> can i work on this

sure go ahead, Figma file has repo readme

**Comment by biswajit-sarkar-007** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by MadhushaPrasad** [comment]
> I would like to work on this issue. Could you please assign it to me?

sure

**Comment by MadhushaPrasad** [comment]
@ANIKETRAJ28 can you assign to ( https://github.com/MadhushaPrasad/Diagon-Alley/issues/25 https://github.com/MadhushaPrasad/Diagon-Alley/issues/24 https://github.com/MadhushaPrasad/Diagon-Alley/issues/23 https://github.com/MadhushaPrasad/Diagon-Alley/issues/22 ) any of these.

**Comment by MadhushaPrasad** [comment]
@DishaKD can you assign to ( https://github.com/MadhushaPrasad/Diagon-Alley/issues/25 https://github.com/MadhushaPrasad/Diagon-Alley/issues/24 https://github.com/MadhushaPrasad/Diagon-Alley/issues/23 https://github.com/MadhushaPrasad/Diagon-Alley/issues/22 ) any of these.

**Comment by biswajit-sarkar-007** [comment]
@MadhushaPrasad ,can  you give me Diagon Alley  Logo !

**Comment by MadhushaPrasad** [comment]
> @MadhushaPrasad ,can you give me Diagon Alley Logo ! it's almost done i just need this logo.

You can get that from our Figma file. It is already in the repo readme file.

**Comment by biswajit-sarkar-007** [comment]
@MadhushaPrasad , Hey, I have submitted a PR in #102; please check it.
