### ISSUE TITLE
SignUp page

### ISSUE THREAD

**Issue by IndudiniThennakoon** [MadhushaPrasad/Diagon-Alley#38]
![Sign Up](https://user-images.githubusercontent.com/99181964/196584124-07376ff0-909e-4558-98fd-f69f2b30a3fa.png)

**Comment by Sandaru-Dev** [comment]
Hi @MadhushaPrasad, Can you assign me to this task as I'm already working on it?
Thank you!

**Comment by MadhushaPrasad** [comment]
> Hi @MadhushaPrasad, Can you assign me to this task as I'm already working on it? Thank you!

done
