### ISSUE TITLE
Implement the contactuUs component in in home page

### ISSUE THREAD

**Issue by MadhushaPrasad** [MadhushaPrasad/Diagon-Alley#83]

**Comment by aayu5hgit** [comment]
Hey @MadhushaPrasad 

I'll implement the required component too.

**Comment by MadhushaPrasad** [comment]
@aayu5hgit This issue is already implemented. Can you assign another issue?

**Comment by MadhushaPrasad** [comment]
@aayu5hgit can you assign to ( https://github.com/MadhushaPrasad/Diagon-Alley/issues/25 https://github.com/MadhushaPrasad/Diagon-Alley/issues/24 https://github.com/MadhushaPrasad/Diagon-Alley/issues/23 https://github.com/MadhushaPrasad/Diagon-Alley/issues/22 ) any of these.

**Comment by aayu5hgit** [comment]
Hey @MadhushaPrasad 

I can do these but are they hacktoberfest accepted?

**Comment by aayu5hgit** [comment]
I'll do this by tomorrow tonight.🙌🏻
